name: detekt
on:
 push:
   branches:
   - develop
 pull_request:
   branches:
   - develop

jobs:
 detekt:
   runs-on: ubuntu-latest
   steps:
      - name: "checkout"
        uses: actions/checkout@v2
      - name: "detekt"
        uses: natiginfo/action-detekt-all@1.23.6
        with:
          args: --config config/detekt/detekt.yml
