name: detekt
on:
 push:
   branches:
   - develop
 pull_request:
   branches:
   - develop

jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Download detekt-formatting plugin"
        run: |
          curl -sSL -o config/detekt/detekt-formatting-1.23.6.jar https://github.com/detekt/detekt/releases/download/v1.23.6/detekt-formatting-1.23.6.jar

      - name: "Run detekt"
        uses: natiginfo/action-detekt-all@1.23.6
        with:
          args: --build-upon-default-config --config config/detekt/detekt.yml -plugins config/detekt/detekt-formatting-1.23.6.jar