name: detekt
on:
 push:
   branches:
   - develop
 pull_request:
   branches:
   - develop

jobs:
  detekt:
    name: Detekt Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK and Gradle cache
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-platform: 'android-34'

      - name: Run Detekt
        run: |
          ./gradlew detekt
